# This is a workflow to test and deploy our app.

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  PYTHONPATH: ${{ github.workspace }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python 3.13
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
          architecture: 'x64'

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install MongoDB in a Docker container.
        uses: supercharge/mongodb-github-action@1.8.0

      - name: Install Python packages.
        run: make dev_env

      - name: Test server
        run: cd server && make tests

      - name: Test data
        run: cd data && make tests

      - name: Test security
        run: cd security && make tests
